AudioVolume/Controllers/ArticleController.cs
using AudioVolume.DAL;
using AudioVolume.Models;
using AudioVolume.ViewModel;
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
namespace AudioVolume.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        private IEnumerable<ArticleCategory> ArticleCategories => _unitOfWork.ArticleCategoryRepository.Get();

        #region ArticleCategory
        [ChildActionOnly]
        public ActionResult ListCategory()
        {
            var allcats = _unitOfWork.ArticleCategoryRepository.Get(orderBy: q => q.OrderBy(a => a.CategorySort));
            return PartialView(allcats);
        }
        public ActionResult ArticleCategory(string result = "")
        {
            ViewBag.ArticleCat = result;
            ViewBag.RootCats = new SelectList(
                    _unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null, q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            var articleCat = new ArticleCategory { CategorySort = 1, CategoryActive = true };

            return View(articleCat);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult ArticleCategory(ArticleCategory model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);
                    var fixSizeImage = HtmlHelpers.FixedSize(newImage, 1000, 1000, false);
                    HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);

                    if (Request.Files.Keys[i] == "Image")
                    {
                        model.Image = imgFile;
                    }
                }

                model.Url = HtmlHelpers.ConvertToUnSign(null, model.Url ?? model.CategoryName);

                _unitOfWork.ArticleCategoryRepository.Insert(model);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "success" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(model);
        }
        public ActionResult UpdateCategory(int catId = 0)
        {
            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return RedirectToAction("ArticleCategory");
            }

            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateCategory(ArticleCategory category, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);
                    var fixSizeImage = HtmlHelpers.FixedSize(newImage, 1000, 1000, false);
                    HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);

                    if (Request.Files.Keys[i] == "Image")
                    {
                        category.Image = imgFile;
                    }
                }

                var file = Request.Files["Image"];

                if (file != null && file.ContentLength == 0)
                {
                    category.Image = fc["CurrentFile"] == "" ? null : fc["CurrentFile"];
                }

                category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                _unitOfWork.ArticleCategoryRepository.Update(category);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "update" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null, q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public bool DeleteCategory(int catId = 0)
        {

            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return false;
            }
            _unitOfWork.ArticleCategoryRepository.Delete(category);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateArticleCat(int sort = 1, bool active = false, bool menu = false, bool footer = false, int articleCatId = 0)
        {
            var articleCat = _unitOfWork.ArticleCategoryRepository.GetById(articleCatId);
            if (articleCat == null)
            {
                return false;
            }
            articleCat.CategorySort = sort;
            articleCat.CategoryActive = active;
            articleCat.ShowMenu = menu;
            articleCat.ShowFooter = footer;

            _unitOfWork.Save();
            return true;
        }
        #endregion

        #region Article
        public ActionResult ListArticle(int? page, string name, int? catId, int? childId, string result = "")
        {
            ViewBag.Result = result;
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var article = _unitOfWork.ArticleRepository.GetQuery(orderBy: l => l.OrderByDescending(a => a.Id));

            if (childId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == childId);
            }
            else if (catId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == catId || l.ArticleCategory.ParentId == catId);
            }
            if (!string.IsNullOrEmpty(name))
            {
                article = article.Where(l => l.Subject.Contains(name));
            }
            var model = new ListArticleViewModel
            {
                SelectCategories = new SelectList(ArticleCategories.Where(a => a.ParentId == null), "Id", "CategoryName"),
                Articles = article.ToPagedList(pageNumber, pageSize),
                CatId = catId,
                ChildId = childId,
                Name = name
            };

            if (catId.HasValue)
            {
                model.ChildCategoryList =
                    new SelectList(ArticleCategories.Where(a => a.ParentId == catId), "Id", "CategoryName");
            }
            return View(model);
        }
        public ActionResult Article()
        {
            var model = new InsertArticleViewModel
            {
                Categories = ArticleCategories,
                Article = new Article { Active = true }
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Article(InsertArticleViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articles/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);

AudioVolume/Controllers/BannerController.cs
using AudioVolume.DAL;
using AudioVolume.Models;
using AudioVolume.ViewModel;
using Helpers;
using PagedList;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
namespace AudioVolume.Controllers
{

    [Authorize]
    public class BannerController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        public ActionResult ListBanner(int? page, int groupId = 0, string result = "")
        {
            ViewBag.Banner = result;
            var pageNumber = page ?? 1;
            const int pageSize = 10;
            var banners = _unitOfWork.BannerRepository.GetQuery(orderBy: q => q.OrderBy(a => a.GroupId).ThenBy(a => a.Sort));
            if (groupId > 0)
            {
                banners = banners.Where(a => a.GroupId == groupId);
            }
            var model = new ListBannerViewModel
            {
                Banners = banners.ToPagedList(pageNumber, pageSize),
            };
            return View(model);
        }
        public ActionResult Banner()
        {
            var model = new BannerViewModel()
            {
                Banner = new Banner() { Sort = 1, Active = true }
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Banner(BannerViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;
                var file = Request.Files["Banner.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg|mp4"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg, mp4");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 100000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 100MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                            var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(file.FileName)) +
                                "-" + DateTime.Now.Millisecond + Path.GetExtension(file.FileName);

                            model.Banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }
                if (isPost)
                {
                    model.Banner.ListImage = fc["Pictures"];
                    _unitOfWork.BannerRepository.Insert(model.Banner);
                    _unitOfWork.Save();

                    return RedirectToAction("ListBanner", new { result = "success" });
                }
            }
            return View(model);
        }
        public ActionResult EditBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return RedirectToAction("ListBanner");
            }
            var model = new BannerViewModel
            {
                Banner = banner,
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult EditBanner(BannerViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                var isPost = true;

                var banner = _unitOfWork.BannerRepository.GetById(model.Banner.Id);

                var file = Request.Files["Banner.Image"];
                if (file != null && file.ContentLength > 0)
                {
                    if (!HtmlHelpers.CheckFileExt(file.FileName, "jpg|jpeg|png|gif|svg|mp4"))
                    {
                        ModelState.AddModelError("", @"Chỉ chấp nhận định dạng jpg, png, gif, jpeg, svg, mp4");
                        isPost = false;
                    }
                    else
                    {
                        if (file.ContentLength > 100000 * 1024)
                        {
                            ModelState.AddModelError("", @"Dung lượng lớn hơn 100MB. Hãy thử lại");
                            isPost = false;
                        }
                        else
                        {
                            var imgPath = "/images/banners/" + DateTime.Now.ToString("yyyy/MM/dd");
                            HtmlHelpers.CreateFolder(Server.MapPath(imgPath));
                            var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(file.FileName)) +
                                "-" + DateTime.Now.Millisecond + Path.GetExtension(file.FileName);

                            banner.Image = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;
                            file.SaveAs(Server.MapPath(Path.Combine(imgPath, imgFileName)));
                        }
                    }
                }

                if (isPost)
                {
                    banner.ListImage = fc["Pictures"] == "" ? null : fc["Pictures"];
                    banner.GroupId = model.Banner.GroupId;
                    banner.BannerName = model.Banner.BannerName;
                    banner.Slogan = model.Banner.Slogan;
                    banner.Sort = model.Banner.Sort;
                    banner.Active = model.Banner.Active;
                    banner.Url = model.Banner.Url;
                    banner.Content = model.Banner.Content;

                    _unitOfWork.BannerRepository.Update(banner);
                    _unitOfWork.Save();

                    return RedirectToAction("ListBanner", new { result = "update" });
                }
            }
            return View(model);
        }
        [HttpPost]
        public bool DeleteBanner(int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            HtmlHelpers.DeleteFile(Server.MapPath("/images/banners/" + banner.Image));
            _unitOfWork.BannerRepository.Delete(banner);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateBannerQuick(int sort = 1, bool active = false, int bannerId = 0)
        {
            var banner = _unitOfWork.BannerRepository.GetById(bannerId);
            if (banner == null)
            {
                return false;
            }
            banner.Sort = sort;
            banner.Active = active;

            _unitOfWork.Save();
            return true;
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

AudioVolume/Views/Mms/ChangePassword.cshtml
@model AudioVolume.ViewModel.ChangePasswordModel
@{
    ViewBag.Title = "Đổi mật khẩu";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="page-title">
        <i class="fa-solid fa-align-right fa-rotate-180 fa-sm"></i>
        <span>Thay đổi mật khẩu</span>
    </div>
    <a href="#" onclick="history.go(-1)" class="btn-main btn-labeled bg-brown">
        <span class="icon">
            <i class="fa-solid fa-left"></i>
        </span>
        Quay lại
    </a>
</div>
<div class="content">
    @if (ViewBag.Result == 1)
    {
        <div id="AlertBox" class="alert alert-success"><strong>Đổi mật khẩu thành công</strong></div>
    }
    <div class="accordion">
        <div class="accordion-item border-left-slate">
            <div class="accordion-header">
                <div class="card-title">
                    <i class="fa-light fa-pen-to-square fa-lg"></i>
                    Thay đổi mật khẩu
                </div>
                <button type="button" data-bs-toggle="collapse" data-bs-target="#editForm" aria-expanded="true">
                    <i class="fa-solid fa-angle-down"></i>
                </button>
            </div>
            <div id="editForm" class="accordion-collapse collapse show">
                <div class="accordion-body">
                    @using (Html.BeginForm("ChangePassword", "Mms", FormMethod.Post, new { @id = "data-insert-form" }))
                    {
                        @Html.ValidationSummary(true)
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="OldPassword">Mật khẩu hiện tại <span class="text-danger">*</span></label>
                            <div class="col-lg-9">
                                @Html.PasswordFor(a => a.OldPassword, new { @class = "form_control" })
                                @Html.ValidationMessageFor(a => a.OldPassword)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="Password">Mật khẩu mới <span class="text-danger">*</span></label>
                            <div class="col-lg-9">
                                @Html.PasswordFor(a => a.Password, new { @class = "form_control" })
                                @Html.ValidationMessageFor(a => a.Password)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="ConfirmPassword">Nhập lại mật khẩu</label>
                            <div class="col-lg-9">
                                @Html.PasswordFor(a => a.ConfirmPassword, new { @class = "form_control w300" })
                                @Html.ValidationMessageFor(a => a.ConfirmPassword)
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="reset" onclick="resetAnyFormById('data-insert-form');" class="btn-main btn-white" id="reset">
                                <span>Đặt lại</span>
                                <i class="fa-solid fa-rotate-right ms-2"></i>
                            </button>
                            <button type="submit" class="btn-main btn-primary text-white ms-3">
                                <span>Lưu</span>
                                <i class="fa-solid fa-floppy-disk ms-2"></i>
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

AudioVolume/Views/Mms/CreateAdmin.cshtml
@model AudioVolume.Models.Admin
@{
    ViewBag.Title = "Thêm quản trị";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="page-header">
    <div class="page-title">
        <span>Thêm quản trị</span>
    </div>
    <a href="#" onclick="history.go(-1)" class="btn-main btn-labeled bg-brown">
        <span class="icon">
            <i class="fas fa-long-arrow-left"></i>
        </span>
        Quay lại
    </a>
</div>
<div class="content">
    @if (ViewBag.Result == "success")
    {
        <div id="AlertBox" class="alert alert-success"><strong>Thêm mới admin thành công</strong></div>
    }
    @if (ViewBag.Result == "update")
    {
        <div id="AlertBox" class="alert alert-success"><strong>Cập nhật admin thành công</strong></div>
    }
    <div class="accordion">
        <div class="accordion-item border-left-slate">
            <div class="accordion-header">
                <div class="card-title">
                    <i class="fa-light fa-octagon-plus fa-lg"></i>
                    Thêm quản trị
                </div>
                <button type="button" data-bs-toggle="collapse" data-bs-target="#createForm" aria-expanded="true">
                    <i class="fa-solid fa-angle-down"></i>
                </button>
            </div>
            <div id="createForm" class="accordion-collapse collapse show">
                <div class="accordion-body">
                    @using (Html.BeginForm("CreateAdmin", "Mms", FormMethod.Post, new { @id = "data-insert-form" }))
                    {
                        @Html.ValidationSummary(true)
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="Username">Tên đăng nhập <span class="text-danger">*</span></label>
                            <div class="col-lg-9">
                                @Html.EditorFor(a => a.Username)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="Password">Mật khẩu <span class="text-danger">*</span></label>
                            <div class="col-lg-9">
                                @Html.EditorFor(a => a.Password)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            @Html.LabelFor(a => a.Active, new { @class = "col-form-label col-lg-3" })
                            <div class="col-lg-9">
                                <label class="form-check-label">
                                    <input type="checkbox" name="Active" value="true" checked />
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="reset" onclick="resetAnyFormById('data-insert-form');" class="btn-main btn-white" id="reset">
                                <span>Đặt lại</span>
                                <i class="fa-solid fa-rotate-right ms-2"></i>
                            </button>
                            <button type="submit" class="btn-main btn-primary text-white ms-3">
                                <span>Lưu</span>
                                <i class="fa-solid fa-floppy-disk ms-2"></i>
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
        @Html.Action("ListAdmin", "Mms")
    </div>
</div>

AudioVolume/Views/Mms/EditAdmin.cshtml
@model AudioVolume.ViewModel.EditAdminViewModel
@{
    ViewBag.Title = "Cập nhật quản trị";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <div class="page-title">
        <span>Cập nhật quản trị</span>
    </div>
    <a href="#" onclick="history.go(-1)" class="btn-main btn-labeled bg-brown">
        <span class="icon">
            <i class="fas fa-long-arrow-left"></i>
        </span>
        Quay lại
    </a>
</div>
<div class="content">
    <div class="accordion">
        <div class="accordion-item border-left-slate">
            <div class="accordion-header">
                <div class="card-title">
                    <i class="fa-light fa-octagon-plus fa-lg"></i>
                    Cập nhật quản trị
                </div>
                <button type="button" data-bs-toggle="collapse" data-bs-target="#editForm" aria-expanded="true">
                    <i class="fa-solid fa-angle-down"></i>
                </button>
            </div>
            <div id="editForm" class="accordion-collapse collapse show">
                <div class="accordion-body">
                    @using (Html.BeginForm("EditAdmin", "Mms", FormMethod.Post))
                    {
                        @Html.ValidationSummary(true)
                        <div class="mb-3 row">
                            <label class="col-form-label col-lg-3" for="Username">Tên đăng nhập <span class="text-danger">*</span></label>
                            <div class="col-lg-9">
                                @Html.EditorFor(a => a.Username)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            @Html.LabelFor(a => a.Password, new { @class = "col-form-label col-lg-3" })
                            <div class="col-lg-9">
                                @Html.EditorFor(a => a.Password)
                            </div>
                        </div>
                        <div class="mb-3 row">
                            @Html.LabelFor(a => a.Active, new { @class = "col-form-label col-lg-3" })
                            <div class="col-lg-9">
                                <label class="form-check-label">
                                    <input type="checkbox" name="Active" @if (Model.Active) { @Html.Raw("value='true' checked")  } else { @Html.Raw("value='false'") } />
                                    <span class="checkmark"></span>
                                </label>
                            </div>
                        </div>
                        <div class="btn-group">
                            <button type="submit" class="btn-main btn-primary text-white">
                                <span>Lưu</span>
                                <i class="fa-solid fa-floppy-disk ms-2"></i>
                            </button>
                        </div>
                    }
                </div>
            </div>
        </div>
        @Html.Action("ListAdmin", "Mms")
    </div>
</div>

AudioVolume/Views/Mms/Index.cshtml
@model AudioVolume.ViewModel.InfoAdminViewModel
@{
    ViewBag.Title = "Welcome to website";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="content">
    <div class="row mt-4">
        <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
            <div class="overview-item">
                <div class="icon"><i class="fal fa-user"></i></div>
                <a class="stretched-link" href="@Url.Action("CreateAdmin", "Mms")">Quản trị viên</a>
                <p class="counter">@Model.Admins</p>
                <div class="info">
                    <i class="far fa-edit me-1"></i> Có thể thay đổi thông tin website
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
            <div class="overview-item">
                <div class="icon icon-product"><i class="fal fa-box"></i></div>
                <a class="stretched-link" href="@Url.Action("ListProduct", "Product")">Sản phẩm</a>
                <p class="counter">@Model.Products</p>
                <div class="info">
                    <i class="fal fa-shopping-cart me-1"></i> Cập nhật liên tục
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
            <div class="overview-item">
                <div class="icon icon-article"> <i class="fal fa-newspaper"></i></div>
                <a class="stretched-link" href="@Url.Action("ListArticle", "Article")">Tin tức</a>
                <p class="counter">@Model.Articles</p>
                <div class="info">
                    <i class="far fa-history me-1"></i> Tin tức mới nhất
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
            <div class="overview-item">
                <div class="icon icon-cart"><i class="fal fa-ad"></i></div>
                <a class="stretched-link" href="@Url.Action("ListBanner", "Banner")">Quảng cáo</a>
                <p class="counter">@Model.Banners</p>
                <div class="info">
                    <i class="far fa-history me-1"></i> Cập nhật liên tục
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-3 mt-md-5 mt-3">
            <div class="overview-item">
                <div class="icon icon-city"><i class="fal fa-mailbox"></i></div>
                <a class="stretched-link" href="@Url.Action("ListContact", "Contact")">Liên hệ</a>
                <p class="counter">@Model.Contacts</p>
                <div class="info">
                    <i class="far fa-history me-1"></i> Cập nhật mới nhất
                </div>
            </div>
        </div>
    </div>
</div>