AudioVolume/Controllers/ArticleController.cs
using AudioVolume.DAL;
using AudioVolume.Models;
using AudioVolume.ViewModel;
using Helpers;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
namespace AudioVolume.Controllers
{
    [Authorize]
    public class ArticleController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        private IEnumerable<ArticleCategory> ArticleCategories => _unitOfWork.ArticleCategoryRepository.Get();

        #region ArticleCategory
        [ChildActionOnly]
        public ActionResult ListCategory()
        {
            var allcats = _unitOfWork.ArticleCategoryRepository.Get(orderBy: q => q.OrderBy(a => a.CategorySort));
            return PartialView(allcats);
        }
        public ActionResult ArticleCategory(string result = "")
        {
            ViewBag.ArticleCat = result;
            ViewBag.RootCats = new SelectList(
                    _unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null, q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            var articleCat = new ArticleCategory { CategorySort = 1, CategoryActive = true };

            return View(articleCat);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult ArticleCategory(ArticleCategory model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);
                    var fixSizeImage = HtmlHelpers.FixedSize(newImage, 1000, 1000, false);
                    HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);

                    if (Request.Files.Keys[i] == "Image")
                    {
                        model.Image = imgFile;
                    }
                }

                model.Url = HtmlHelpers.ConvertToUnSign(null, model.Url ?? model.CategoryName);

                _unitOfWork.ArticleCategoryRepository.Insert(model);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "success" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(model);
        }
        public ActionResult UpdateCategory(int catId = 0)
        {
            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return RedirectToAction("ArticleCategory");
            }

            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(l => l.ParentId == null, a => a.OrderBy(c => c.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult UpdateCategory(ArticleCategory category, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articleCategory/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);
                    var fixSizeImage = HtmlHelpers.FixedSize(newImage, 1000, 1000, false);
                    HtmlHelpers.SaveJpeg(Server.MapPath(Path.Combine(imgPath, imgFileName)), fixSizeImage, 90);

                    if (Request.Files.Keys[i] == "Image")
                    {
                        category.Image = imgFile;
                    }
                }

                var file = Request.Files["Image"];

                if (file != null && file.ContentLength == 0)
                {
                    category.Image = fc["CurrentFile"] == "" ? null : fc["CurrentFile"];
                }

                category.Url = HtmlHelpers.ConvertToUnSign(null, category.Url ?? category.CategoryName);
                _unitOfWork.ArticleCategoryRepository.Update(category);
                _unitOfWork.Save();
                return RedirectToAction("ArticleCategory", new { result = "update" });
            }
            ViewBag.RootCats = new SelectList(_unitOfWork.ArticleCategoryRepository.Get(a => a.ParentId == null, q => q.OrderBy(a => a.CategorySort)), "Id", "CategoryName");
            return View(category);
        }
        [HttpPost]
        public bool DeleteCategory(int catId = 0)
        {

            var category = _unitOfWork.ArticleCategoryRepository.GetById(catId);
            if (category == null)
            {
                return false;
            }
            _unitOfWork.ArticleCategoryRepository.Delete(category);
            _unitOfWork.Save();
            return true;
        }
        public bool UpdateArticleCat(int sort = 1, bool active = false, bool menu = false, bool footer = false, int articleCatId = 0)
        {
            var articleCat = _unitOfWork.ArticleCategoryRepository.GetById(articleCatId);
            if (articleCat == null)
            {
                return false;
            }
            articleCat.CategorySort = sort;
            articleCat.CategoryActive = active;
            articleCat.ShowMenu = menu;
            articleCat.ShowFooter = footer;

            _unitOfWork.Save();
            return true;
        }
        #endregion

        #region Article
        public ActionResult ListArticle(int? page, string name, int? catId, int? childId, string result = "")
        {
            ViewBag.Result = result;
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var article = _unitOfWork.ArticleRepository.GetQuery(orderBy: l => l.OrderByDescending(a => a.Id));

            if (childId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == childId);
            }
            else if (catId.HasValue)
            {
                article = article.Where(l => l.ArticleCategoryId == catId || l.ArticleCategory.ParentId == catId);
            }
            if (!string.IsNullOrEmpty(name))
            {
                article = article.Where(l => l.Subject.Contains(name));
            }
            var model = new ListArticleViewModel
            {
                SelectCategories = new SelectList(ArticleCategories.Where(a => a.ParentId == null), "Id", "CategoryName"),
                Articles = article.ToPagedList(pageNumber, pageSize),
                CatId = catId,
                ChildId = childId,
                Name = name
            };

            if (catId.HasValue)
            {
                model.ChildCategoryList =
                    new SelectList(ArticleCategories.Where(a => a.ParentId == catId), "Id", "CategoryName");
            }
            return View(model);
        }
        public ActionResult Article()
        {
            var model = new InsertArticleViewModel
            {
                Categories = ArticleCategories,
                Article = new Article { Active = true }
            };
            return View(model);
        }
        [HttpPost, ValidateInput(false)]
        public ActionResult Article(InsertArticleViewModel model, FormCollection fc)
        {
            if (ModelState.IsValid)
            {
                for (var i = 0; i < Request.Files.Count; i++)
                {
                    if (Request.Files[i] == null || Request.Files[i].ContentLength <= 0) continue;
                    if (!HtmlHelpers.CheckFileExt(Request.Files[i].FileName, "jpg|jpeg|png|gif")) continue;
                    if (Request.Files[i].ContentLength > 1024 * 1024 * 4) continue;

                    var imgFileName = HtmlHelpers.ConvertToUnSign(null, Path.GetFileNameWithoutExtension(Request.Files[i].FileName)) +
                        "-" + DateTime.Now.Millisecond + Path.GetExtension(Request.Files[i].FileName);
                    var imgPath = "/images/articles/" + DateTime.Now.ToString("yyyy/MM/dd");
                    HtmlHelpers.CreateFolder(Server.MapPath(imgPath));

                    var imgFile = DateTime.Now.ToString("yyyy/MM/dd") + "/" + imgFileName;

                    var newImage = Image.FromStream(Request.Files[i].InputStream);

AudioVolume/Controllers/ContactController.cs
using AudioVolume.DAL;
using AudioVolume.Models;
using AudioVolume.ViewModel;
using Helpers;
using PagedList;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;
namespace AudioVolume.Controllers
{

    [Authorize]
    public class ContactController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        #region Contact
        public ActionResult ListContact(int? page, string name)
        {
            var pageNumber = page ?? 1;
            const int pageSize = 15;
            var contacts = _unitOfWork.ContactRepository.GetQuery(orderBy: l => l.OrderByDescending(a => a.Id));

            if (!string.IsNullOrEmpty(name))
            {
                contacts = contacts.Where(l => l.Mobile.Contains(name));
            }
            var model = new ListContactViewModel
            {
                Contacts = contacts.ToPagedList(pageNumber, pageSize),
                Name = name
            };
            return View(model);
        }
        [HttpPost]
        public bool DeleteContact(int contactId = 0)
        {
            var contact = _unitOfWork.ContactRepository.GetById(contactId);
            if (contact == null)
            {
                return false;
            }
            _unitOfWork.ContactRepository.Delete(contact);
            _unitOfWork.Save();
            return true;
        }
        #endregion

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

AudioVolume/Views/Shared/_AdminIframeLayout.cshtml
@using AudioVolume.Models
@{
    var config = (ConfigSite)HttpContext.Current.Application["ConfigSite"];
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" /> 
    @*<meta name="viewport" content="width=device-width" />*@
    <title>@ViewBag.Title</title>
    <link rel="shortcut icon" href="~/favicon.png">
    @Styles.Render("~/Content/admincss", "~/Content/themes/base/css")
    <link href="~/Scripts/multi-upload/jquery.fileupload.css" rel="stylesheet" /> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    @RenderBody()
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/bundles/jqueryui")
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/Scripts/multi-upload/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/multi-upload/jquery.fileupload.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.toast.js"></script>
    <script src="~/Scripts/ckeditor/adapters/jquery.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <script src="~/Scripts/scriptAdmin.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

AudioVolume/Views/Shared/_AdminLayout.cshtml
@using AudioVolume.Models
@{ var config = (ConfigSite)HttpContext.Current.Application["ConfigSite"]; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @*<meta name="viewport" content="width=device-width" />*@
    <title>@ViewBag.Title</title>
    @*@if (config.Favicon != null)
    {
        <link rel="shortcut icon" href="@Path.Combine("/images/configs/", config.Favicon)?w=64&h=64">
    }*@
    @Styles.Render("~/Content/admincss", "~/Content/themes/base/css")
    <link href="~/Scripts/multi-upload/jquery.fileupload.css" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-dark">
        <div class="navbar-brand">
            @if (config.Image != null)
            {
                <a href="@Url.Action("Index","Home")" target="_blank" class="d-inline-block">
                    <img src="@Path.Combine("/images/configs/", config.Image)" alt="logo" />
                </a>
            }
        </div>
        <div class="navbar-collapse">
            <div class="paragraph-justify">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="@Url.Action("ListContact","Contact")" class="navbar-nav-link">
                        <i class="fa-solid fa-envelope fa-xl"></i>
                        <span id="header_notification_count">0</span>
                    </a>
                </li>
                <li class="nav-item">
                    <div class="dropdown-user navbar-nav-link">
                        <img src="~/Content/images/admin/icon_profile.png" alt="avatar" />
                        <h5 class="mb-0">@User.Identity.Name</h5>
                        <i class="fa-regular fa-angle-down"></i>
                    </div>
                    <div class="drop">
                        <div class="content-drop">
                            <a href="@Url.Action("ConfigSite","Mms")"><i class="fal fa-info-circle"></i>Thông tin chung</a>
                            <a href="@Url.Action("ChangePassword","Mms")"><i class="fal fa-low-vision"></i>Đổi mật khẩu</a>
                            <a href="@Url.Action("LogOut","Mms")"><i class="fal fa-sign-out-alt"></i>Đăng xuất</a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="page-content">
        <div class="sidebar">
            <div class="scrollbar-target">
                <ul class="nav-sidebar">
                    <li class="nav-item" data-id="1">
                        <a href="@Url.Action("Index","Mms")" class="nav-link">
                            <i class="fas fa-home-lg-alt"></i>
                            <span>Tổng quan website</span>
                        </a>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="2">
                        <a href="javascript:;" class="nav-link">
                            <i class="fas fa-user-cog"></i>
                            <span>Admin</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("ChangePassword", "Mms")" class="nav-link">
                                    <i class="fas fa-eye-slash"></i>
                                    <span>Đổi mật khẩu</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("CreateAdmin", "Mms")" class="nav-link">
                                    <i class="fal fa-user-plus"></i>
                                    <span>Quản lý admin</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ConfigSite", "Mms")" class="nav-link">
                                    <i class="fas fa-key"></i>
                                    <span>Thông tin chung</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Logout", "Mms")" class="nav-link">
                                    <i class="fal fa-sign-out-alt"></i>
                                    <span>Đăng xuất</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="3">
                        <a href="javascript:;" class="nav-link">
                            <i class="fas fa-box"></i>
                            <span>Quản lý sản phẩm</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("ProductCategory", "Product")" class="nav-link">
                                    <i class="fa-light fa-share-nodes fa-rotate-90"></i>
                                    <span>Danh mục sản phẩm</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Product", "Product")" class="nav-link">
                                    <i class="fa-light fa-square-plus"></i>
                                    <span>Thêm mới sản phẩm</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ListProduct", "Product")" class="nav-link">
                                    <i class="fa-thin fa-grid"></i>
                                    <span>Danh sách sản phẩm</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="3">
                        <a href="javascript:;" class="nav-link">
                            <i class="fa-solid fa-rectangles-mixed"></i>
                            <span>Quản lý thương hiệu</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("Brand", "Product")" class="nav-link">
                                    <i class="fa-light fa-square-plus"></i>
                                    <span>Thêm mới thương hiệu</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Brand", "Product")#brand" class="nav-link">
                                    <i class="fa-thin fa-grid"></i>
                                    <span>Danh sách thương hiệu</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="7">
                        <a href="javascript:;" class="nav-link">
                            <i class="fa-solid fa-shop"></i>
                            <span>Quản lý chi nhánh</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("Showroom", "Article")" class="nav-link">
                                    <i class="fa-light fa-image"></i>
                                    <span>Thêm mới chi nhánh</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="5">
                        <a href="javascript:;" class="nav-link">
                            <i class="fa-light fa-newspaper"></i>
                            <span>Quản lý Bài viết</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("ArticleCategory", "Article")" class="nav-link">
                                    <i class="fa-light fa-share-nodes fa-rotate-90"></i>
                                    <span>Danh mục bài viết</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Article", "Article")" class="nav-link">
                                    <i class="fa-light fa-square-plus"></i>
                                    <span>Thêm mới bài viết</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ListArticle", "Article")" class="nav-link">
                                    <i class="fa-thin fa-grid"></i>
                                    <span>Danh sách bài viết</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="7">
                        <a href="javascript:;" class="nav-link">
                            <i class="fa-solid fa-image"></i>
                            <span>Quản lý Banner</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("Banner", "Banner")" class="nav-link">
                                    <i class="fa-light fa-image"></i>
                                    <span>Thêm mới banner</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ListBanner", "Banner")" class="nav-link">
                                    <i class="fa-light fa-images"></i>
                                    <span>Danh sách banner</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item nav-item-submenu" data-id="8">
                        <a href="javascript:;" class="nav-link">
                            <i class="fa-solid fa-envelope"></i>
                            <span>Quản lý Liên hệ</span>
                        </a>
                        <ul class="nav-group-sub">
                            <li class="nav-item">
                                <a href="@Url.Action("ListContact", "Contact")" class="nav-link">
                                    <i class="fa-light fa-envelope"></i>
                                    <span>Danh sách liên hệ</span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content-wrapper">
            <div class="main-content">
                @RenderBody()
            </div>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/bundles/jqueryui")
    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/Scripts/multi-upload/jquery.iframe-transport.js"></script>
    <script src="~/Scripts/multi-upload/jquery.fileupload.js"></script>
    <script src="~/Scripts/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.toast.js"></script>
    <script src="~/Scripts/ckeditor/adapters/jquery.js"></script>
    <script src="~/Scripts/jquery.cookie.js"></script>
    <script src="~/Scripts/jquery.fancybox.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5-qrcode/2.3.8/html5-qrcode.min.js" integrity="sha512-r6rDA7W6ZeQhvl8S7yRVQUKVHdexq+GAlNkNNqVC7YyIV+NwqCTJe2hDWCiffTyRNOeGEzRRJ9ifvRm/HCzGYg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/Scripts/scriptAdmin.js"></script>
    @RenderSection("scripts", false)
</body>
</html>

AudioVolume/Views/Shared/_ArticleItem.cshtml
@model AudioVolume.Models.Article

<div class="news-item">
    <a href="@Url.Action("ArticleDetail", new { url = Model.Url })" class="news-img">
        @if (Model.Image != null)
        {
            <img data-src="@Path.Combine("/images/articles/", Model.Image)" src="~/Content/images/img-main/base64.gif" alt="@Model.Subject" class="lazyload" />
        }
        else
        {
            <img src="~/Content/images/img-main/on-image.jpg" alt="@Model.Subject" />
        }
    </a>
    <div class="body">
        <div class="subject">
            <a href="@Url.Action("ArticleDetail", new { url = Model.Url })" title="@Model.Subject">@Model.Subject</a>
        </div>
        <div class="desc">
            @Model.Description
        </div>
    </div>
</div>

AudioVolume/Views/Shared/_Layout.cshtml
@using AudioVolume.Models
@{
    var config = (ConfigSite)HttpContext.Current.Application["ConfigSite"];
}
<!DOCTYPE html>
<html lang="vi-VN">
<head xmlns="http://www.w3.org/1999/xhtml" prefix="og:http://ogp.me/ns# fb:http://www.facebook.com/2008/fbml">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Refresh" content="300">
    <title>@ViewBag.Title</title>
    <meta name="description" content="@Html.Raw(ViewBag.Description)" />
    <meta name="robots" content="@(ViewBag.Robots == null ? "follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large" : ViewBag.Robots)" />
    <meta http-equiv="Content-Language" content="en">
    <link rel="canonical" href="@ViewBag.Canonical" />
    @if (ViewBag.Prev != null)
    {
        <link rel="prev" href="@ViewBag.Prev" />
    }
    @if (ViewBag.Next != null)
    {
        <link rel="next" href="@ViewBag.Next" />
    }
    @if (config.Favicon != null)
    {
        <link rel="shortcut icon" href="@Path.Combine("/images/configs/", config.Favicon)?w=64&h=64">
    }
    <meta property="og:locale" content="vi_VN">
    <meta property="og:type" content="website">
    <meta property="og:title" content="@Html.Raw(ViewBag.Title)">
    <meta property="og:description" content="@Html.Raw(ViewBag.Description)">
    <meta property="og:url" content="@ViewBag.Canonical">
    <meta property="og:site_name" content="@Html.Raw(ViewBag.Title)">
    <meta property="og:image" content="@(ViewBag.ImageShare ?? Request.Url?.GetLeftPart(UriPartial.Authority) + Path.Combine("/images/configs/", config.Image))" />
    <meta property="og:image:alt" content="@ViewBag.Title" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">

    @Styles.Render("~/Content/css")

    @if (config.GoogleAnalytics != null)
    {
        @Html.Raw(config.GoogleAnalytics)
    }
</head>
<body>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.css" integrity="sha512-X/RSQYxFb/tvuz6aNRTfKXDnQzmnzoawgEQ4X8nZNftzs8KFFH23p/BA6D2k0QCM4R0sY1DEy9MIY9b3fwi+bg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    @Html.Action("Header", "Home")
    @RenderBody()
    @Html.Action("Footer", "Home")
    @Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval")
    <script src="~/Scripts/bootstrap.bundle.js"></script>
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
    <script src="https://cdnjs.cloudflare.com/ajax/libs/owl-carousel/1.3.3/owl.carousel.min.js" integrity="sha512-9CWGXFSJ+/X0LWzSRCZFsOPhSfm6jbnL+Mpqo0o8Ke2SYr8rCTqb4/wGm+9n13HtDE1NQpAEOrMecDZw4FXQGg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5aWh3zgiZpsm7Ir38aCou0RWjept_TiQ&libraries=places"></script>
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v14.0" nonce="di1pgAbX"></script>

</body>
</html>

AudioVolume/Views/Shared/_ProductSearchResults.cshtml
@model AudioVolume.ViewModel.SearchQuickViewModel
    @{ 
        var count = Model.Products.Count() - 5;
    }
<ul>
    @if (Model.Products.Any())
    {
        foreach (var item in Model.Products.Take(5))
        {
            <li>
                <a href="@Url.Action("ProductDetail", new {url= item.Url})">
                    @if (item.Image != null)
                    {
                        <img src="@Path.Combine("/images/products/", item.Image)">
                    }
                    <p>@item.Name</p>
                    <p>
                        @if (item.PriceSale > 0)
                        {
                            <span class="search-pro-price-new">
                                @item.PriceSale
                            </span>
                        }
                        else if (item.Price > 0)
                        {
                            <span class="search-pro-price-new">
                                @item.Price
                            </span>
                        }
                        else
                        {
                            <span class="search-pro-price-new">
                                Liên hệ
                            </span>
                        }
                    </p>
                </a>
            </li>
        }
        <li class="total-search-product"><a href="@Url.Action("Search", new {keysearch = Model.Keysearch})">Xem thêm @count sản phẩm phù hợp</a></li>
    }
    else
    {
        <li class="text-danger">@ViewBag.Message</li>
    }

</ul>